### ISSUE TITLE
Add support for Cloud Scheduler

### ISSUE THREAD

**Issue by watchinharrison** [GoogleCloudPlatform/magic-modules#1096]
See: https://github.com/terraform-providers/terraform-provider-google/issues/2571

**Comment by ocervell** [comment]
@watchinharrison Any progress made here ? Support for Cloud Scheduler would be awesome.

**Comment by domZippilli** [comment]
@ocervell looks like it is in PR here https://github.com/GoogleCloudPlatform/magic-modules/pull/1102

@watchinharrison lmk if I can help. Excited to see this get merged. I could use it right this moment!

**Comment by watchinharrison** [comment]
@ocervell @domZippilli A downstream has been generated for the provider repo https://github.com/terraform-providers/terraform-provider-google-beta/pull/378, just waiting on approval for that and it'll be ready for use

**Comment by watchinharrison** [comment]
This has been merged now on this and the beta provider repo. Just waiting on the next release for the google-beta provider

**Comment by rileykarson** [comment]
Closed by https://github.com/GoogleCloudPlatform/magic-modules/pull/1102
