### ISSUE TITLE
support update mask in MM natively

### ISSUE THREAD

**Issue by chrisst** [GoogleCloudPlatform/magic-modules#1142]
Several different resources now use update mask and they appear to all be using it consistently enough that it could be a first party magic modules feature.

Currently supported in terraform with [custom code](https://github.com/GoogleCloudPlatform/magic-modules/search?q=update_mask&unscoped_q=update_mask)

Example apis that use update mask:
https://cloud.google.com/access-context-manager/docs/reference/rest/v1beta/accessPolicies/patch
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs/patch

Note: There are still subtle differences like context manager _requires_ that update mask is present but uptimeCheckConfigs only lists it as optional. But both should work correctly if it's always passed.

**Comment by chrisst** [comment]
Also note that the current Terraform implementation doesn't support nested fields.

**Comment by chrisst** [comment]
I think you're asking about supporting nesting, in which case:

I suppose this might be more of a bug with how `input` fields are added into patch bodies. Right now if there is a change in `topfield.sub` and `topfield` is `input` and the request is a PATCH, it won't detect the change on `sub` and therefore will exclude the whole `topfield` block from the request body. If we end up resolving that bug by sending sending the only the nested field that changed we will need to also change update mask to support that.

**Comment by rileykarson** [comment]
Resolved by @rambleraptor with https://github.com/GoogleCloudPlatform/magic-modules/pull/1178
