### ISSUE TITLE
Add labels to PR based on which provider it affects

### ISSUE THREAD

**Issue by rosbo** [GoogleCloudPlatform/magic-modules#124]
- Create one label for each provider: puppet, chef, terraform & ansible.
- Add labels automatically to MM PRs based on which repo they are impacting.

As a reviewer with an expertise in a particular provider (Terraform in my case), I can quickly see if any PRs requires my attention and also see what's coming up in terms of new feature for the provider I care about.

**Comment by rileykarson** [comment]
@rambleraptor this is what you're working on, right?

**Comment by rambleraptor** [comment]
I didn't realize there was a bug for this! Yeah, that's what I'm doing.
