### ISSUE TITLE
Don't run the CI pipeline on the Magician's commits updating the submodule 

### ISSUE THREAD

**Issue by rosbo** [GoogleCloudPlatform/magic-modules#125]
After all the downstream PRs have been merged, the Magician creates a new commit to update the submodules in the MM repo and then merge the PR into master.

This commit however triggers a full run of the pipeline. 

We could add a special tag in the description of a commit to update submodule automatically created by the magician and don't trigger the pipeline if the tag is present in the description.

**Comment by rileykarson** [comment]
@ndmckinley Was this solved by the automerged label?

**Comment by ndmckinley** [comment]
Oh yeah, I did do that, thanks.  Good catch.
