### ISSUE TITLE
Open new PR to downstream repo if new changes create a diff in that repo

### ISSUE THREAD

**Issue by rosbo** [GoogleCloudPlatform/magic-modules#130]
Scenario:
- I open MM module PR 999
- It impacts terraform and puppet-compute
- The puppet-compute PR is accepted and I merged it
- I realized that terraform is broken and I need to fix MM PR 999
- I update MM PR 999 this causes change to both downstream repos
- Terraform repo is updated, the PR is accepted and I merge it.
- However, the puppet-compute PR was already merged and the change is lost.

The next PR will catchup puppet-compute but that would be nicer if a new PR was open against puppet-compute for the case described above.

**Comment by ndmckinley** [comment]
Fixed in #1400.

![image](https://user-images.githubusercontent.com/605324/52891485-203c4700-3140-11e9-9983-91988809d946.png)
