### ISSUE TITLE
Update of password with ansible module gcp_sql_user not possible

### ISSUE THREAD

**Issue by dabde** [GoogleCloudPlatform/magic-modules#1349]
hi,

I'm try to use `gcp_sql_user` module, to change the password of the already existing "postgres" user, if you create a new postgres instance. Sadly, it does not work. 

I know the fact, that you can't compare the password at all. So my workaround currently is, to patch the python file to update the user every time.

I don't know, what's maybe here the best practice. But to maintain an existing setup, the module is nearly not usable.

Thanks.

**Comment by rileykarson** [comment]
Hey @dabde!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible repo](https://github.com/ansible/ansible/issues/new/choose). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.

**Comment by dabde** [comment]
Hey @rileykarson,

then maybe I now a little bit confused. MM is generate the ansible modules and point out in the files to look here for here (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gcp_sql_user.py#L12).

So if the file point to here and you point to ansible ... sound for me like a endless loop for fixing this issue. :-/

**Comment by rileykarson** [comment]
Issues should be filed against the specific tools' issues, but you're correct that changes to generated files need to happen in this repo, so pull requests should land here. By filing against specific tools, issues with the GCP plugin for that tool live alongside other plugins, and core project maintainers (eg Ansible proper) have visibility into the issues users are having.

The Ansible downstream is nearly entirely generated, so there's a weird line between tool-specific and Magic Modules-level issues, but with some of our other downstreams there's a large body of non-generated code that *can* be changed in the target repo.

**Comment by TomaszKlosinski** [comment]
Apparently the module doesn't implement 'update' for Google Cloud PostgreSQL database. I'm facing the same issue and I think I'll just work around it with removing user and adding it again. Or I'll just switch to terraform as it seems to have better support for clouds APIs.
