### ISSUE TITLE
Add StackStorm provider

### ISSUE THREAD

**Issue by cognifloyd** [GoogleCloudPlatform/magic-modules#1480]
I would love to see a StackStorm pack for GCP on http://exchange.stackstorm.com.

In StackStorm (ST2), actions are discrete elements that can be combined into larger actions called workflows. A pack contains all of the actions used to integrate with a particular service provider, in this case, GCP.

GCP actions might include creating or listing GCP project, updating IAM policies, or creating compute engine nodes. An action consists of a yaml metadata file (describing available parameters) and a python script that does the work of the action. (actually any language can be used for the actions, not just python. Python is merely the default as ST2 is written in python.)

Typically for a project like GCP with a lot of related APIs, the ST2 actions are auto-generated somehow. magic-modules looks like the perfect generator to build these actions.
Unlike Ansible, we can use any Google Cloud python libraries to simplify writing the ST2 pack. Each ST2 pack gets its own python virtual environment including any requirements on pypi. So, the GCP pack only needs to be a light wrapper around one of the libraries that already exists.

### Info about creating a StackStorm pack of GCP actions

- about actions: https://docs.stackstorm.com/actions.html
- writing a action metadata: https://docs.stackstorm.com/actions.html#writing-custom-actions
- writing a python action: https://docs.stackstorm.com/actions.html#writing-custom-python-actions
- writing packs: https://docs.stackstorm.com/packs.html#developing-a-pack
- pack writing/submitting tutorial: https://docs.stackstorm.com/reference/packs.html
- where exchange.stackstorm.com packs live: https://github.com/StackStorm-Exchange

### Google Cloud's Python libs:

Generic info about the python libs:

- https://googleapis.github.io/google-cloud-python/
- https://github.com/googleapis/google-cloud-python

The specific python libs (in the order I would like to see the actions - but if anyone can help, please do whatever order makes sense to you):

- https://pypi.org/project/google-cloud-resource-manager/ (particularly actions for project lifecycle)
- https://github.com/googleapis/google-api-python-client (use for a subset of discovery apis focused on infrastructure where other python libs aren't available: IAM, compute engine, app engine)
- https://pypi.org/project/google-cloud-container/
- https://pypi.org/project/google-cloud-storage/
- https://pypi.org/project/google-cloud-dns/

At some point, I suppose the google-api-python-client could be used in a variety of different packs for things like drive, gmail, etc. But, here, I'm asking for the help managing things that have to do with Google Cloud Platorm (Resource Manager, IAM, Compute Engine, and other infrastructural type toolsets).

**Comment by rambleraptor** [comment]
Hello! Thanks a lot for bringing this to us. StackStorm looks like it would be a good fit with Magic Modules. We've done past Magic Modules work using the REST APIs instead of client libraries, but the generator is flexible enough that you could use client libraries. It might be easier to do this without Magic Modules, since the ST2 packs would be a wrapper around the client libraries.

Sadly, we don't have enough bandwidth to take this on. If you'd like to submit PRs, we'd be happy to merge them in.

**Comment by cognifloyd** [comment]
Awesome. Some ST2 packs have a little generator that builds the actions - but there isn't any automation to keep those packs up-to-date. So, getting magic-modules to build the pack would be far better than trying to roll-my-own generator.

I did not realize that all of the Magic Modules work directly with the REST APIs. I've only used the Ansible modules, but I assumed that those didn't use the libraries so that target hosts didn't have to have pip dependencies installed first.

So, thinking about how it might work to use the REST APIs directly, ST2 has a variety of action runners, of which python is only one. Another runner is the _HTTP Runner_ which does just as it sounds, it turns HTTP requests into actions. We might be able to use that, though I expect to run into caveats and edge cases with an API as extensive as GCPs.

HTTP Runner details:
- [runner docs](https://docs.stackstorm.com/reference/runners.html#http-runner-http-request)
- [runner pre-defined parameters (yaml)](https://github.com/StackStorm/st2/blob/master/contrib/runners/http_runner/http_runner/runner.yaml)
- [the runner's python code](https://github.com/StackStorm/st2/blob/master/contrib/runners/http_runner/http_runner/http_runner.py)

Examples of actions that use the HTTP Runner
- [http.core](https://github.com/StackStorm/st2/blob/master/contrib/core/actions/http.yaml)
- [examples.weather](https://github.com/StackStorm/st2/blob/master/contrib/examples/actions/weather.yaml)

If the HTTP Runner doesn't prove to be flexible enough, then we can either
- write the actions as python actions (What most packs do today)
- write a new runner, possibly extending the http runner, just for GCP actions.

The first method requires generating at least one action-metadata yaml file and one python file per action, while the second approach only needs the action-metadata yaml file (in addition to the runner).
