### ISSUE TITLE
API.yaml should indicate if a resource can be updated

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#154]
Ansible currently has a `editable` field that indicates if a resource can be edited or not.

We should consider porting this field over to api.yaml so that the rest of the providers can get access to it.

**Comment by danawillow** [comment]
We already have this with the custom update logic. Here's how we determine updatable in TF: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/provider/terraform.rb#L57

**Comment by rambleraptor** [comment]
I'm closing this. Seems like we have a better update story now.
