### ISSUE TITLE
Support for multiple API versions

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#155]
Terraform will handle this by having a different repo per API version. The other providers, for now, will only support GA APIs. Once the support exists, we can figure out exactly how the other providers will handle it.

Implementation will be as per design proposal.

**Comment by rambleraptor** [comment]
Can we close this?

**Comment by danawillow** [comment]
At least right now, I believe Terraform is the only provider that supports non-GA products/features. So we should probably have a story for the others. I'll close it, and then if people decide they'd like the other providers to support non-GA features they can open a bug specifically for that provider.
