### ISSUE TITLE
Allow simpler local testing of downstream tools

### ISSUE THREAD

**Issue by rileykarson** [GoogleCloudPlatform/magic-modules#1563]
Developing MM locally can be a little frustrating. When I make a change to a provider and want to test it, I need to run a big command:

```
bundle exec compiler -a -e terraform -o "${GOPATH}/src/github.com/terraform-providers/terraform-provider-google-beta/" -v "beta"
```

and then wait 30s-80s, then a testing command in the same directory I just specified. Even worse, that directory never changes.

```
make testacc TEST=./google-beta TESTARGS='-run=TestAccSqlDatabaseInstance_basicSecondGen'
```

We should add a `rake` command that simplifies the build & test workflow in the common cases.

This should include some simple aliases for common patterns;

`rake build terraform` => `bundle exec compiler -a -e terraform -o "${GOPATH}/src/github.com/terraform-providers/terraform-provider-google/" -v "ga`

`rake build terraform-beta` => `bundle exec compiler -a -e terraform -o "${GOPATH}/src/github.com/terraform-providers/terraform-provider-google-beta/" -v "beta`

`rake build terraform-beta --test "TestAccSqlDatabaseInstance_basicSecondGen"` => 
```
bundle exec compiler -a -e terraform -o "${GOPATH}/src/github.com/terraform-providers/terraform-provider-google-beta/" -v "beta
cd "${GOPATH}/src/github.com/terraform-providers/terraform-provider-google-beta/" # or whatever the safe to run version of cd in a script is
make testacc TEST=./google-beta TESTARGS='-run=TestAccSqlDatabaseInstance_basicSecondGen'
```

This saves developers a context switch and makes the simple case of development _much_ easier for new developers, instead of needing to parse https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools then read provider-specific instructions at https://github.com/GoogleCloudPlatform/magic-modules#testing-your-changes

**Comment by slevenick** [comment]
Does this not exist already?

I run `bundle exec rake compile:inspec` to build InSpec, and I don't think I've modified the Rakefile

**Comment by rileykarson** [comment]
`bundle exec rake compile:terraform` compiles to `build/terraform` and not the GOPATH & the run fails to copy common/compiled files for me; as well, the testing feature would be novel.

**Comment by slevenick** [comment]
Hm, yeah seems like it needs to be specific to each provider. As each will build and test in different ways

**Comment by leg100** [comment]
@rileykarson It's no silver bullet, but specifying the 'product' you're make changes to can speed it up somewhat:

```
$ time bundle exec compiler -a -v "beta" -e terraform -o "$HOME/go/src/github.com/terraform-providers/terraform-provider-google-beta"

real	0m31.518s
user	0m44.129s
sys	0m2.394s
```
```
$ time bundle exec compiler -p products/storage -v "beta" -e terraform -o "$HOME/go/src/github.com/terraform-providers/terraform-provider-google-beta"
real	0m5.855s
user	0m17.328s
sys	0m1.335s
```
