### ISSUE TITLE
Add Support For Cloud Firestore

### ISSUE THREAD

**Issue by abombss** [GoogleCloudPlatform/magic-modules#1578]
We need support for Cloud Firestore now that it is has gone GA.
There is a REST based API and discovery document available [here](https://firestore.googleapis.com/$discovery/rest?version=v1).

I am a little unclear how Firestore is actually integrated with GCP compared to native Firebase, but our goal would be to provision and manage Firestore databases, collections, indexes and authN / authZ via Terraform within our GCP projects.

**Comment by abombss** [comment]
Is closed with #1682, or do we keep it open until we have full support for enabling the service too?

**Comment by rileykarson** [comment]
I'd say leave open until we can enable the service.

**Comment by plebasaurus** [comment]
+1, it seems like #1682 doesn't support creating a collection, only indices.

**Comment by rileykarson** [comment]
Closing in favour of the Terraform repo issue.
