### ISSUE TITLE
INSPEC Support for google cloud function

### ISSUE THREAD

**Issue by callppatel** [GoogleCloudPlatform/magic-modules#1583]
Currently there is not INSPEC resource to validate resource google_cloudfunctions_function where need to validate if my function is created with correct memory, timeout, entrypoint etc. Please help to set-up Inspec function.

**Comment by rileykarson** [comment]
Hey @callppatel! We track issues against specific tools in their respective repo; InSpec already has an issue filed for Cloud Functions: https://github.com/inspec/inspec-gcp/issues/124.
