### ISSUE TITLE
MM is authoritative for terraform-google-conversion

### ISSUE THREAD

**Issue by rileykarson** [GoogleCloudPlatform/magic-modules#1626]
@chrisst do you think it's worth spending some cycles here? eg https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/52

**Comment by chrisst** [comment]
I think it's probably worth seeing if this is an ongoing issue. Since Emily added filtering for the conversion library I'm hoping it won't come up again, but if it does it's a pretty low effort fix.
