### ISSUE TITLE
Add support for BigQuery Scheduled Queries

### ISSUE THREAD

**Issue by cemo** [GoogleCloudPlatform/magic-modules#1628]
Add support for BigQuery Scheduling Queries. It is very crucial to complement some missing parts of BigQuery to create workarounds.

**Comment by rileykarson** [comment]
Hey @cemo! Generally, we try to file bugs against specific tools' repos. Which are you interested in support for?

**Comment by cemo** [comment]
Hey, terraform :)

**Comment by rileykarson** [comment]
Closing this as a dupe of the provider-specific issue: https://github.com/terraform-providers/terraform-provider-google/issues/2028
