### ISSUE TITLE
Create a "swissknife" tool to easily test out any of the supported providers

### ISSUE THREAD

**Issue by rosbo** [GoogleCloudPlatform/magic-modules#168]
Goal: One-liner to spin up a container with credentials setup, and all the providers installed and configured with a shared volume to easily test out new changes to Magic Module for any provider.

Supports:

* [x] Puppet
* [ ] Chef
* [ ] Ansible
* [ ] Terraform

**Comment by rileykarson** [comment]
I don't think we're continuing with this, so I'm going to close it out. OiCS could be useful for similar use cases in the future: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/TUTORIAL.md.
