### ISSUE TITLE
Cloud Function VPC

### ISSUE THREAD

**Issue by watchinharrison** [GoogleCloudPlatform/magic-modules#1691]
## Description

With Cloud Functions having beta support for Serverless VPC (https://cloud.google.com/vpc/docs/configure-serverless-vpc-access) would be good to get the vpcConnector property supported for beta

**Comment by rileykarson** [comment]
Hey @watchinharrison! The specific tool that you'd like support in is the best place to file this issue, so for Terraform that's at https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md (based on the original title of this issue). If we have documentation pointing you here, please let us know- we were in an in between state for where issues like this should go for a while but decided that filing against specific tools was most appropriate.

If you're interested in support across multiple tools, feel free to file against each.
