### ISSUE TITLE
Enable Storage Terraform generation

### ISSUE THREAD

**Issue by nickjacques** [GoogleCloudPlatform/magic-modules#1754]
Hello,

I'm planning on contributing to magic-modules to enable GCS Retention Policies in the Terraform `google_storage_bucket` resource. (Work is already underway to add me to our Corporate CLA). 

My proposed code change will look much like this: https://github.com/GoogleCloudPlatform/magic-modules/compare/master...nickjacques:storage_retention_policy

In short, this will add a `retentionPolicy` nested object that maps to the API spec: https://cloud.google.com/storage/docs/json_api/v1/buckets

However, when compiling for Terraform, these changes are not generated for `resource_storage_bucket.go`. If I alter the exclusion for Terraform bucket objects to be `false` (https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/storage/terraform.yaml#L17), a resource file is generated with the appropriate changes, but then overwritten at the very last part of the compile process. 

My question is twofold:

1. What is the process required to enable this product for Terraform resource generation?
  - It seems like the Terraform provider is currently using a manually constructed file. Is there a blocker to generating this resource with Magic Modules? Should I contribute this in the Terraform module or should I contribute here?
1. If you'd prefer me to contribute to Magic Modules, how can I prevent the generated resource file from being overwritten so I can build and test the Terraform provider?

Apologies if I've overlooked something, I'm new to working with Magic Modules :)

Thanks,
Nick

**Comment by Chupaka** [comment]
Looks like it's still not generated by MM, probably you need to change https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_storage_bucket.go by hands.
