### ISSUE TITLE
Update topic label in Terraform

### ISSUE THREAD

**Issue by bgpat** [GoogleCloudPlatform/magic-modules#1775]
Although I tried to set a label to the pubsub topic, the topic is about to be recreated. Terraform should able to update `labels` property without recreating because Google provides update API.

```
-/+ google_pubsub_topic.foo (new resource required)
    id:           "projects/tetst-project/topics/foo" => "<computed>" (forces new resource)
    labels.%:     "0" => "1" (forces new resource)
    labels.bar:   "" => "bar" (forces new resource)
```

**Comment by rileykarson** [comment]
Do you mind opening this on https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md, including the context that it's in alpha?
