### ISSUE TITLE
Puppet, Chef: cannot assign storage.objects.get permission using gstorage_bucket_access_control

### ISSUE THREAD

**Issue by pegasd** [GoogleCloudPlatform/magic-modules#181]
I came across the issue while using Puppet's `gstorage` module and judging by the documentation, Chef has a similar problem.

There are currently only 3 roles that you can set through the `gstorage_bucket_access_control` type:

- READER
- WRITER
- OWNER

They correspond to "Storage Legacy Bucket *" roles none of which contain the much needed `storage.objects.get` permission.

I'm happy with either one of the following solutions:

- Start supporting non-legacy roles (`Storage Object Viewer` would fit my goal perfectly)
- Start supporting "Storage Legacy Object *" roles (I'll have to use both `Storage Legacy Bucket Reader` and `Storage Legacy Object Reader`)

Either of these will let me get both `storage.objects.get` and `storage.objects.list` permissions.

**Comment by pegasd** [comment]
Related Terraform resources:

- `google_storage_bucket_acl` manages Legacy roles (and also has a `default_acl`` option)
- `google_storage_default_object_acl` manages default object ACLs
- `google_storage_bucket_iam_binding` and `google_storage_bucket_iam_member` manage non-Legacy roles

**Comment by erjohnso** [comment]
@ndmckinley - let's poke at this today and see if we can't get a fix out.

**Comment by ndmckinley** [comment]
I think it'd be tough to get IAM resources working today, but if we're talking quick fixes, it might be possible to get Storage Legacy Object roles working.

@pegasd - do you need default object ACLs, or will the regular object ACL work?

**Comment by pegasd** [comment]
@ndmckinley I'm guessing default object ACLs? Which one does `Storage Legacy Object Reader` refer to?
I upload objects to the bucket without setting any specific object ACLs (think `gsutil cp`) - what would I need?

**Comment by ndmckinley** [comment]
Yep, default object ACLs!

**Comment by ndmckinley** [comment]
This is merged downstream.  Please let us know if this works for you!

**Comment by pegasd** [comment]
Bad news!
Seems like it's doing nothing every time I try to apply the catalog:

```
Notice: /Stage[main]/Main/Gstorage_default_object_acl[my_bucket_my-user@my-project.iam.gserviceaccount.com]/bucket: defined 'bucket' as 'my_bucket'
```

This happens every time I apply my manifest (while `gstorage_bucket_access_control` gets applied on the first run).

**Comment by pegasd** [comment]
After some more digging around, it turns out that `defacl` did in fact get set after applying the manifest.

The issue that I described probably refers to an inability to fetch/read default ACL properly.

**Comment by pegasd** [comment]
I also see these when applying:

```
Warning: Event['desired_value'] contains a Google::Storage::Data::BucketNameRefCatalog value. It will be converted to the String 'my_bucket'
```

**Comment by ndmckinley** [comment]
Sorry, I'm pretty new to puppet, so those just look like expected messages to me.  And it does seem that the ACL is getting correctly applied...

I think the first message, the Notice, is telling us which bucket it's using, and the second one, the Warning, is resolving the reference to the bucket.  Can you share the config you're using (redacted of information you don't want to post) and your expected output?

**Comment by pegasd** [comment]
Here is the sample code I used for tests:

```puppet
gauth_credential { 'my_cred':
  path     => $cred_path,
  provider => serviceaccount,
  scopes   => [
    'https://www.googleapis.com/auth/devstorage.full_control',
  ],
}

gstorage_bucket { 'test_bucket':
  location   => 'US',
  project    => $gcp_project,
  credential => 'my_cred',
}

gstorage_default_object_acl { 'test_bucket_acl':
  bucket     => 'test_bucket',
  entity     => "user-my_service_account@${gcp_project}.iam.gserviceaccount.com",
  role       => 'READER',
  project    => $gcp_project,
  credential => 'my_cred',
}
```

Let's try running it with `--noop` first (no changes will be made at this point):

```
Notice: Compiled catalog for localhost in environment production in 0.31 seconds
Notice: /Stage[main]/Main/Gstorage_bucket[test_bucket]/ensure: current_value 'absent', should be 'present' (noop)
Notice: /Stage[main]/Main/Gstorage_default_object_acl[test_bucket_acl]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Class[Main]: Would have triggered 'refresh' from 2 events
Notice: Stage[main]: Would have triggered 'refresh' from 1 event
Notice: Applied catalog in 0.89 seconds
```

This looks perfectly OK to me.

Now let's actually apply the manifest:

```
Notice: Compiled catalog for localhost in environment production in 0.30 seconds
Notice: /Stage[main]/Main/Gstorage_bucket[test_bucket]/ensure: created
Notice: /Stage[main]/Main/Gstorage_default_object_acl[test_bucket_acl]/ensure: created
Notice: Applied catalog in 5.28 seconds
```

Even better. Seems like we've got everything done.

Now, if I run the code again, I expect to see no changes - the bucket is created and default ACL was set.

Let's try it with `--noop`:

```
Notice: Compiled catalog for localhost in environment production in 0.30 seconds
Notice: /Stage[main]/Main/Gstorage_default_object_acl[test_bucket_acl]/bucket: current_value 'absent', should be 'test_bucket' (noop)
Notice: Class[Main]: Would have triggered 'refresh' from 1 event
Notice: Stage[main]: Would have triggered 'refresh' from 1 event
Notice: Applied catalog in 2.76 seconds
Warning: Event['desired_value'] contains a Google::Storage::Data::BucketNameRefCatalog value. It will be converted to the String 'test_bucket'
Warning: Event['desired_value'] contains a Google::Storage::Data::BucketNameRefCatalog value. It will be converted to the String 'test_bucket'
```

This doesn't look good - seems like it's attempting to set the `bucket` value to `test_bucket` instead of `absent`.

I'm not entirely sure what this is supposed to do. If the ACL's `bucket` parameter is unset - what did the code do in the first place?

Let's try to actually apply it:

```
Notice: Compiled catalog for localhost in environment production in 0.30 seconds
Notice: /Stage[main]/Main/Gstorage_default_object_acl[test_bucket_acl]/bucket: defined 'bucket' as 'test_bucket'
Notice: Applied catalog in 0.93 seconds
Warning: Event['desired_value'] contains a Google::Storage::Data::BucketNameRefCatalog value. It will be converted to the String 'test_bucket'
Warning: Event['desired_value'] contains a Google::Storage::Data::BucketNameRefCatalog value. It will be converted to the String 'test_bucket'
```

Hmm, it looks like it did something. Still not sure what exactly, but let's try applying it again:

```
Notice: Compiled catalog for localhost in environment production in 0.30 seconds
Notice: /Stage[main]/Main/Gstorage_default_object_acl[test_bucket_acl]/bucket: defined 'bucket' as 'test_bucket'
Notice: Applied catalog in 0.91 seconds
Warning: Event['desired_value'] contains a Google::Storage::Data::BucketNameRefCatalog value. It will be converted to the String 'test_bucket'
Warning: Event['desired_value'] contains a Google::Storage::Data::BucketNameRefCatalog value. It will be converted to the String 'test_bucket'
```

And this keeps happening every time I re-run my manifest.

The output I would expect at this point is this:

```
Notice: Compiled catalog for localhost in environment production in 0.30 seconds
Notice: Applied catalog in 0.91 seconds
```

**Comment by pegasd** [comment]
While writing acceptance tests for Puppet code, my approach is to use the following wrapper function to test for idempotence (similar approach could be used to catch issues like this at testing stage):

```ruby
def apply_and_test_idempotence(manifest)
  context 'applying manifest and testing for idempotence' do
    it 'does not fail the first time around' do
      apply_manifest(manifest, catch_failures: true)
    end

    it 'does not change anything on the second run' do
      apply_manifest(manifest, catch_changes: true)
    end
  end
end
```

This makes sure that no failures occur when I run the manifest for the first time and no changes happen on the second run.

**Comment by pegasd** [comment]
That’s a tad out of scope of what I’m prepared to post at a public repository, sorry.
Do you know the specific part you’re interested in?

**Comment by pegasd** [comment]
[This](https://github.com/GoogleCloudPlatform/puppet-google-storage/pull/16) PR did the trick, thanks!

**Comment by ndmckinley** [comment]
:)
