### ISSUE TITLE
Storage Transfer Service required parameters change

### ISSUE THREAD

**Issue by akramhussein** [GoogleCloudPlatform/magic-modules#1837]
Hi,

In [google_storage_transfer_job](https://www.terraform.io/docs/providers/google/r/storage_transfer_job.html) is the `schedule.schedule_end_date` now a required block?

I have updated to provider version `2.7.0` and I tried adding a new s3 -> GCS bucket transfer and I'm receiving an error:

```
* google_storage_transfer_job.s3_bucket_backup.12: googleapi: Error 400: Schedule end date: Invalid year specified. Year must be between 1 and 9999 inclusive., badRequest
```

I checked the API docs [here] and don't see any changes.

I wrote the original implementation of this with help from @rileykarson - so if someone is able to confirm it is now a required field, I can create the PRs here and `beta` for the doc changes and required field changes.

**Comment by rileykarson** [comment]
We're not aware of any changes, although that doesn't mean there are none. Has the same config worked previously?

Issues with specific providers are best filed against the actual downstream tool repo, so in this case would you mind refiling to https://github.com/terraform-providers/terraform-provider-google/issues/new?template=bug.md?

**Comment by akramhussein** [comment]
Will do.

Yes - I have 15 jobs running since December 2018 untouched. Suddenly adding a new one doesn’t work.

Kind regards,

Akram
