### ISSUE TITLE
data resource for google_compute_ha_vpn_gateway

### ISSUE THREAD

**Issue by gtmtech** [GoogleCloudPlatform/magic-modules#1838]
Hi, terraform question:

I'm a newcomer to magic-modules, but needed to use some support for `google_compute_ha_vpn_gateway`. However I need to lookup an already established `google_compute_ha_vpn_gateway`, and there is no datasource available in the magic-modules project, although there is a resource. 

More generally, I see this project is all about autogenerating stuff - doesn't it make sense to create the data source alongside the resource for all autogenerated terraform? 

More specifically, could we get a `google_compute_ha_vpn_gateway` data source. The `google_compute_vpn_gateway` non-ha data source does not find HA gateways via the google provider.

**Comment by slevenick** [comment]
Hey there!

Yeah, autogeneration for datasources is not currently supported, but would be very much in the spirit of Magic Modules! As this is more of a feature request for Terraform, I would direct you to make a request on the google provider itself: https://github.com/terraform-providers/terraform-provider-google

I've created https://github.com/GoogleCloudPlatform/magic-modules/issues/1839 for general datasource generation enhancements
