### ISSUE TITLE
Ansible: gcp_iam_service_account_key: python3 TypeError

### ISSUE THREAD

**Issue by cscheib** [GoogleCloudPlatform/magic-modules#1893]
Issue documented here as well:
https://github.com/ansible/ansible/issues/57546

Basically, when it comes time to write out the key content to a file, the content is in 'bytes' form... we need to either modify the file open to write in binary mode (which accepts 'bytes'), or decode the content to a string.

https://github.com/GoogleCloudPlatform/magic-modules/blob/54a75eb5b1f8fe044e356d80a1600db32f7fc7b7/products/iam/helpers/ansible/service_account_key_template.erb#L76-L81

**Comment by cscheib** [comment]
Submitted both possible solutions that I'm aware of for PR/review.

**Comment by rileykarson** [comment]
Thanks for filing @cscheib! We prefer to file issues against the downstream provider's repo, so let's use https://github.com/ansible/ansible/issues/57546 as the canonical issue for this.
