### ISSUE TITLE
Add support for DLP

### ISSUE THREAD

**Issue by abombss** [GoogleCloudPlatform/magic-modules#1915]
We would like support for DLP so we can auto create jobs when we are creating GCS buckets and BQ tables.  It looks like the API is available https://cloud.google.com/dlp/docs/reference/rest/.

**Comment by chrisst** [comment]
@abombss we track feature requests for specific resources in the downstream repositories that they will be added to. For instance if you are looking for support for DLP Terraform please add an issue to https://github.com/terraform-providers/terraform-provider-google. This will help us know which tool to prioritize when building the feature.

The issue tracker in this repository contains improvements and bugs in the code generator itself.
