### ISSUE TITLE
Terraform import generation doesn't allow complex fields.

### ISSUE THREAD

**Issue by chrisst** [GoogleCloudPlatform/magic-modules#1946]
When generating import regexs for an id such as `import_format: ["{{dataset}}/dicomStores/{{name}}"]` if the `dataset` variable contains a self_link style id the import will parse incorrectly.

ex:
an id such as "projects/my-project/locations/us-central/datasets/my-dataset/dicomStores/my-dicom"
where the {{dataset}} is  `projects/my-project/locations/us-central/datasets/my-dataset` will fail because the regex will match only the last part of the path as the `dataset` variable.

The fully qualified import id with variables for project/location/etc isn't feasible if the resource doesn't have those properties.

**Comment by rileykarson** [comment]
There's nominal progress on this related to URL encoding in https://github.com/GoogleCloudPlatform/magic-modules/pull/1866. It didn't end up working exactly as intended-I think some import formats don't collapse correctly-but a solution will look similar.

**Comment by ferrarimarco** [comment]
Hi! Is there a way to work around this issue? It's something that's slowing me down in #3637 

Thanks!

**Comment by rileykarson** [comment]
Not really. I believe it's possible to handwrite the import function, which would let you use a custom regex. That's probably the best option.
