### ISSUE TITLE
ML Engine

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#2061]
- [x] Models in Ansible (https://github.com/GoogleCloudPlatform/magic-modules/pull/2062)
- [x] Versions in Ansible (https://github.com/GoogleCloudPlatform/magic-modules/pull/2068)
- [ ] Models in TF (https://github.com/GoogleCloudPlatform/magic-modules/pull/2071)
- [ ] Versions in TF
- [ ] Models in InSpec
- [ ] Versions in InSpec

**Comment by rileykarson** [comment]
Closing this out since we decided a while ago not to track individual provider implementations / GCP features here.
