### ISSUE TITLE
Support GlobalPolicyEvaluationMode (Binary Authorization)

### ISSUE THREAD

**Issue by mrtyler** [GoogleCloudPlatform/magic-modules#2092]
I'm using https://www.terraform.io/docs/providers/google/r/binary_authorization_policy.html via the (beta) terraform-provider-google.

That resource does not support [globalPolicyEvaluationMode](https://cloud.google.com/binary-authorization/docs/reference/rest/v1beta1/projects.policy#GlobalPolicyEvaluationMode) (aka the "Trust all Google-provided system images" checkbox in the "Binary Authorization -> Edit Policy" page in the GCP Console).

It would be great if we could manage this setting with Terraform code.

If I understand things correctly, this feature would be implemented in this repo and the Terraform provider would get the feature "for free". But if this feature request should (also) be an issue in the provider repo, please let me know and I am happy to file it there.

**Comment by rileykarson** [comment]
Hey @mrtyler!

We use the issues in this repo primarily for code generator features, and track GCP features on individual provider repos. I'm going to close this issue out- would you mind filing with https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md?

**Comment by mrtyler** [comment]
Re-filed as https://github.com/terraform-providers/terraform-provider-google/issues/4104.
