### ISSUE TITLE
ConfigureBasePaths function is not available in third_party/validator

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/magic-modules#2133]
The ConfigureBasePaths function is required for third_party/validator. It is currently generated correctly in third_party/terraform/utils/provider.go.erb but it is missing in third_party/validator. Without that, third_party/validator is not going to work as all the basePaths would be missing.

**Comment by rileykarson** [comment]
`ConfigureBasePaths` can be moved from provider.go to config.go I think, if that would help. Previously it caused test failures in the conversion lib, but now that it's actually generated it will be safe to add.

**Comment by rileykarson** [comment]
Fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/2181
