### ISSUE TITLE
Track/enforce multiple reviewer approvals for PR

### ISSUE THREAD

**Issue by nelsonjr** [GoogleCloudPlatform/magic-modules#217]
Depending of the kind of change to the MM codebase (provider, product, core, or combinations of) there may be required multiple approvers to ensure the change is properly reviewed by the appropriate teams. (see [GOVERNANCE](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/GOVERNANCE.md) for more details).

To ensure review conditions are satisfied The Magician could track the necessary approvers and flag the PR as "ready to commit" once the proper approvals are secured.

A few ideas:

- **Google OWNERS style:** reviewers would be listed in a file (OWNERS) and depending on each part of the code touched the proper reviewers would be required

```
# Magic Modules OWNERS file

# Magic Modules codebase
provider/: @nelsona @rosbo
provider/puppet/...: @alexstephen
provider/terraform/...: @danawillow
... etc ...

# Product codebase
build/chef/...: @rambleraptor
... etc ...
```

- **Notation on the PR message:** here the PR owner would add a block on the message to notify the relevant people. Something like this:

```
This PR changes the async.erb used by multiple products

Reviewers:
  - core: @nelsona
  - puppet/compute: @rambleraptor
  - terraform: @danawillow
```

- **A combination of both OWNERS and PR message:** the obvious choice to have maximum flexibility. If both OWNERS and PR message are listed, then the union of both must be satisfied.

Once one person of each affected group gives a LGTM, The Magician would write to the PR informing it is safe to proceed with the rebase/merge.

**Comment by ndmckinley** [comment]
I think this has been implemented as closely as possible (1 non-author LGTM, magician generation successful, no merging by hand if the merge commit has changed) with the github restrictions, and writing a new way to track restrictions with Concourse might be more trouble than it's worth, all things considered.  What do you think, @SirGitsalot?

**Comment by SirGitsalot** [comment]
SGTM.
