### ISSUE TITLE
Mildly unintuitive example autogeneration in puppet / chef

### ISSUE THREAD

**Issue by ndmckinley** [GoogleCloudPlatform/magic-modules#220]
Right now, when you write an example for puppet / chef, it ends up in the `examples` directory of the generated submodule, which is great.  The resource : example map is automagic for regular compilation (`README.md`, for instance), but the `examples` `HashArray` in the `puppet.yaml` file could be removed.  We could probably just compile and copy all the examples in that folder rather than require them to be listed.

**Comment by rambleraptor** [comment]
Hijacking this issue to add my own quirks:

* Let's get rid of the e2e tests because we don't actually use them!! Nathan's work will be replacing the `.tests` folder stuff + we can simplify the codebase a lot.

**Comment by rileykarson** [comment]
Seems outdated to me.
