### ISSUE TITLE
Q3 Resources

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#2205]
This is an ongoing list of resources that have been added in Q3.

(`q3` indiciates resource added this quarter, `x` indicates it existed before Q3)

|Resource Name | Ansible | TF | InSpec | 
|--------------|---------|----|--------|
|Cloud Functions | q3 | x | x |
|Compute Snapshots | q3 | x |x |
|Compute Autoscalers| q3 | x | x |
|Cloud Task Queues | q3 | | |
|App Engine Firewall Rules | q3 | x | |
| ML Engine Versions | q3 | | |
| ML Engine Models | q3 | q3 | q3 |
| Cloud Filestore | q3 | x | |
| KMS KeyRings| q3 | x | x |
| KMS CryptoKeys| q3 | x | x |
| AppEngine Standard App Version | | q3 | q3 |
| Stackdriver Organization Log Sink | | x | q3 |

**Comment by rileykarson** [comment]
Q3 is over.
