### ISSUE TITLE
expandIamConfiguration in storage_bucket.go panics

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/magic-modules#2234]
The code actual panics when a nil interface is passing in:

```
        panic: interface conversion: interface {} is nil, not bool

        goroutine 1 [running]:
        github.com/GoogleCloudPlatform/terraform-google-conversion/google.expandIamConfiguration(...)
        	<redacted>/GoogleCloudPlatform/terraform-google-conversion/google/storage_bucket.go:269
```

The code in line 269 in my local snapshot is same as https://github.com/GoogleCloudPlatform/magic-modules/blame/e6b8eca0203975ecad275fb93fa9d4ece1537a33/third_party/validator/storage_bucket.go#L269

```
			Enabled:         d.Get("bucket_policy_only").(bool),
```

**Comment by rileykarson** [comment]
I believe this is resolved by the same fix as #2235, but feel free to reopen / bump this if I'm wrong.
