### ISSUE TITLE
Missing shieldedInstanceConfig on NodeConfig

### ISSUE THREAD

**Issue by NinoFloris** [GoogleCloudPlatform/magic-modules#2250]
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig

```
{
  "enableSecureBoot": boolean,
  "enableIntegrityMonitoring": boolean
}
```

I'd like to enable secure boot so we can enable the shielded vm org policy (which requires all security measures to be enabled) however `NodeConfig` misses the `shieldedInstanceConfig` nested object.

**Comment by rileykarson** [comment]
Hey @NinoFloris! Do you mind filing a feature request against the tool you're interested in instead? We generally don't track features 1-by-1 in this repo, and defer tracking to the tools' issues trackers instead.

**Comment by NinoFloris** [comment]
It's missing in terraform, isn't it the case you do automatic PRs for changes to existing resources?

**Comment by rileykarson** [comment]
Effectively, yep! While we use this repo/tool to manage the codebase for the provider, feature/bug tracking is still done in the provider repo. It looks like an issue has been filed there since this issue was created (https://github.com/terraform-providers/terraform-provider-google/issues/4434).

**Comment by NinoFloris** [comment]
Thanks so much!
