### ISSUE TITLE
container_cluster: `autoprovisioningNodePoolDefaults` missing in `clusterAutoscaling` config

### ISSUE THREAD

**Issue by Dominik-K** [GoogleCloudPlatform/magic-modules#2314]
New [part of the `beta` API](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#autoprovisioningnodepooldefaults)

**Comment by rileykarson** [comment]
Hey @Dominik-K! Do you mind filing a feature request against the tool you're interested in instead? We generally don't track features 1-by-1 in this repo, and defer tracking to the tools' issues trackers instead.

**Comment by Dominik-K** [comment]
Fixed in https://github.com/GoogleCloudPlatform/magic-modules/pull/2747
