### ISSUE TITLE
Appengine Terraform Support multiple Services and Routing

### ISSUE THREAD

**Issue by callppatel** [GoogleCloudPlatform/magic-modules#2327]
Hi - We are looking for terraform resource/property to define URL Dispatch rule to support multi Service applications. 
https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps#UrlDispatchRule

Currently we can do the same by using gcloud by using dispatch.yaml file https://cloud.google.com/appengine/docs/standard/python/reference/dispatch-yaml , we want similar to do with Terraform. 

We are looking for best way to achieve this. Or if there is any effort going to support this thru terraform.

**Comment by callppatel** [comment]
@rileykarson @khanali21  - Could you please review this.

**Comment by rileykarson** [comment]
I think that the best way to implement this would be to add a `google_app_engine_application_url_dispatch_rules` or `google_app_engine_application_url_dispatch_rule` resource, similar to what we're doing in https://github.com/GoogleCloudPlatform/magic-modules/pull/2269.

Config would look something like:

```hcl
resource "google_storage_bucket" "bucket" {
	name = "<%= ctx[:vars]['bucket_name'] %>"
}

resource "google_storage_bucket_object" "object" {
	name   = "hello-world.zip"
	bucket = "${google_storage_bucket.bucket.name}"
	source = "./test-fixtures/appengine/hello-world.zip"
}

resource "google_app_engine_standard_app_version" "myapp_v1" {
  version_id = "v1"
  service = "myapp"
  runtime = "nodejs10"
  noop_on_destroy = true
  entrypoint {
    shell = "node ./app.js"
  }
  deployment {
    zip {
      source_url = "https://storage.googleapis.com/${google_storage_bucket.bucket.name}/hello-world.zip"
    }  
  }
  env_variables = {
    port = "8080"
  } 
  depends_on = ["google_storage_bucket_object.object"]

}

resource "google_app_engine_application_url_dispatch_rules" "service_rules" {
  # project = "my-project"

  dispatch_rule {
    host    = "*"
    path    = "/users/billing"
    service = "billing"
  }

  dispatch_rule {
    host    = "*"
    path    = "/users/*"
    service = "${google_app_engine_standard_app_version.myapp_v2.service}"
  }

  dispatch_rule {
    host    = "admin-console.foobar.com"
    path    = "/*"
    service = "admin"
  }
}
```

**Comment by khanali21** [comment]
@rileykarson Yes that's exactly what it is supposed to be. 
Please review #2338

**Comment by rileykarson** [comment]
I can take a look at #2338 tomorrow, I won't have enough time today to gather context on it.

**Comment by callppatel** [comment]
We can close this as[ this pull](https://github.com/GoogleCloudPlatform/magic-modules/pull/2466) request is completed
