### ISSUE TITLE
Missing option "validateSsl" for Stackdriver uptime monitoring checks

### ISSUE THREAD

**Issue by lushc** [GoogleCloudPlatform/magic-modules#2330]
Related resource: https://www.terraform.io/docs/providers/google/r/monitoring_uptime_check_config.html
Related API documentation: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs#httpcheck

> Boolean specifying whether to include SSL certificate validation as a part of the Uptime check. Only applies to checks where monitoredResource is set to uptime_url. If useSsl is false, setting validateSsl to true has no effect.

**Comment by rileykarson** [comment]
Hey @lushc! Do you mind filing this at https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md instead? This repo isn't really used for requests/issues of this nature, and the Google provider's issue tracker is a better home for this request.
