### ISSUE TITLE
Chef tests are not run by the Magician

### ISSUE THREAD

**Issue by rosbo** [GoogleCloudPlatform/magic-modules#236]
Looking at the chef-test logs:

```
Finished in 0.00081 seconds (files took 0.06931 seconds to load)
0 examples, 0 failures
```

No examples are run for all the product we support in the Magician: compute, sql and storage

https://terraform.ci.cloud-graphite.com/teams/main/pipelines/magic-modules/jobs/chef-test/builds/18

**Comment by rosbo** [comment]
- SPEC_DIR is set to `spec` for chef.
- In `puppet-chef.sh`, we `cd` inside the SPEC_DIR.
- Then we run rspec
- rspec, looks into the `spec` folder but we are already inside the spec folder so the folder doesn't exist and no tests are run

**Comment by rosbo** [comment]
When fixing this `SPEC_DIR` issue in #230, chef-tests ran and I noticed that a lot of tests were failing for chef > 60. I decided to add some logic to skip those for now and this issue will track the work to fix the tests and re-enable them in the Magician.

**Comment by danawillow** [comment]
@ndmckinley is this fixed?

**Comment by ndmckinley** [comment]
Don't think so.
