### ISSUE TITLE
Cloud Run APIs are outdated

### ISSUE THREAD

**Issue by shosti** [GoogleCloudPlatform/magic-modules#2439]
The [Cloud Run APIs](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/cloudrun/api.yaml) are currently using the v1alpha1 API, while [the latest APIs](https://cloud.google.com/run/docs/reference/rest/) are all at v1. I think this may be leading to errors with the `google_cloud_run_domain_mapping` terraform resource (when I try to use it, I get 400 responses with no specifics).

**Comment by rileykarson** [comment]
Deduplicating to https://github.com/terraform-providers/terraform-provider-google/issues/4651
