### ISSUE TITLE
Terraform support for the Cloud Tasks service

### ISSUE THREAD

**Issue by RishiR2** [GoogleCloudPlatform/magic-modules#2468]
HI,
We are looking for terraform support for the Cloud Tasks service like Create Queue, create task, http handler etc..
so want to know if there is any effort is already in place or near release.
thanks,
Rajesh R.

**Comment by rileykarson** [comment]
This is tracked as https://github.com/terraform-providers/terraform-provider-google/issues/2367 and there's an open PR in review at https://github.com/terraform-providers/terraform-provider-google/pull/4529
