### ISSUE TITLE
ML Engine - Terraform resource for Training job & local Train 

### ISSUE THREAD

**Issue by callppatel** [GoogleCloudPlatform/magic-modules#2517]
Currently Terraform for GCP doesnt support ai-platform resources for "training job" & "local train". Do we have this in backlog. If no, then we need your initial guidance so that we can contribute in magic module to enable these two resources.

**Comment by emilymye** [comment]
Opened [an issue](https://github.com/terraform-providers/terraform-provider-google/issues/5272) against Terraform! In the future, please file Terraform-only changes against the Terraform repo, not Magic Modules, as it makes it harder for the Terraform team to track.
