### ISSUE TITLE
Can't build generated terraform providers using master branch

### ISSUE THREAD

**Issue by kopachevsky** [GoogleCloudPlatform/magic-modules#2641]
While testing my PR https://github.com/GoogleCloudPlatform/magic-modules/pull/2592 tried to generate and build terraform providers following this tutorial: https://codelabs.developers.google.com/codelabs/magic-modules/index.html?index=..%2F..index#0

One big issue I found, master branch is broken, can't build providers after code generation.
First, right after generation building both providers got:

```
$ make build
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./google/resource_kms_key_ring.go
./google/resource_compute_region_backend_service_test.go
......
......
./google/resource_compute_disk_resource_policy_attachment.go
./google/resource_compute_region_instance_group_manager_test.go
You can use the command: `make fmt` to reformat code.
GNUmakefile:24: recipe for target 'fmtcheck' failed
make: *** [fmtcheck] Error 
```

So, need to run 'make fmt', did it, and got compilation error after (it's pure masters without my changes)

```
$ cd $GOPATH/src/github.com/terraform-providers/terraform-provider-google 
$ make build                                                         
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go install
import cycle not allowed
package github.com/terraform-providers/terraform-provider-google
	imports github.com/terraform-providers/terraform-provider-google/google
	imports github.com/terraform-providers/terraform-provider-google-beta/google-beta
	imports github.com/terraform-providers/terraform-provider-google-beta/google-beta
../terraform-provider-google-beta/google-beta/config.go:17:2: cannot find package "google.golang.org/api/accesscontextmanager/v1beta" in any of:
	/projects/google/mm/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/google.golang.org/api/accesscontextmanager/v1beta (vendor tree)
	/usr/local/go/src/google.golang.org/api/accesscontextmanager/v1beta (from $GOROOT)
	/projects/google/mm/src/google.golang.org/api/accesscontextmanager/v1beta (from $GOPATH)
GNUmakefile:8: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by danawillow** [comment]
@rileykarson can you look at this or find someone that can? the circular import makes me think of the go modules vendor dir thing.

@kopachevsky, did the `bundle exec compiler` command give you any error messages?

**Comment by rileykarson** [comment]
@kopachevsky: Can you find the branch and commit SHA (from `git log`) you're checked out to in `$GOPATH/src/github.com/terraform-providers/terraform-provider-google`? I suspect it's a fairly old one based on the failure message. The MM SHA would help too (the one before your commits were made, specifically).

MM requires the two to be kept relatively in sync. We've made fairly substantial changes to MM/TPG in the last few days, so I'd suggest rebasing your MM branch to `master` and pulling the latest changes into TPG.

**Comment by kopachevsky** [comment]
@rileykarson I've tried to reproduce this on clean cloud shell env, and got command ` bundle exec compiler -a -v "ga" -e terraform -o "$GOPATH/src/github.com/terraform-providers/terraform-provider-google"` hang on :


```
I, [2019-11-18T14:39:15.251373 #11232]  INFO -- : 'products/vpcaccess' does not have a 'ga' version, skipping
I, [2019-11-18T14:39:15.296172 #11232]  INFO -- : products/kms: Compiling provider config
I, [2019-11-18T14:39:15.602356 #11232]  INFO -- : products/kms: Generating types: ALL
I, [2019-11-18T14:39:15.602706 #11232]  INFO -- : Generating KeyRing
I, [2019-11-18T14:39:16.253810 #11232]  INFO -- : Generating CryptoKey
```

**Comment by kopachevsky** [comment]
@rileykarson do you have exact steps starting from where to clone magic-module repo and what command to call for build somewhere?

**Comment by slevenick** [comment]
Ah, I've seen that command hang before, it's typically due to go modules going off the rails.

If you turn off go modules for the compiler exec command it should work. 

Try adding `GO111MODULE=off` in front of the compiler command, like:
`GO111MODULE=off bundle exec compiler ...`

**Comment by rileykarson** [comment]
@slevenick covered most of my response.

I exclusively use these two commands (subbing beta for GA when needed):

* `GO111MODULE=off time bundle exec compiler -a -e terraform -o "${GOPATH}/src/github.com/terraform-providers/terraform-provider-google" -v "ga"` from the MM dir
* `make build` from the target dir

**Comment by morgante** [comment]
If those commands are required to have a working config, could we update the Codelab to include them?

**Comment by rileykarson** [comment]
Seems reasonable- I'll publish a note about `GO111MODULE=off`. We figured `goimports` hanging while in module mode was a bug but it's been a couple Go releases since then, so that's unlikely to change.

**Comment by kopachevsky** [comment]
@rileykarson  it seems **time** here is not needed? 
`GO111MODULE=off time bundle exec compiler -a -e terraform -o "${GOPATH}/src/github.com/terraform-providers/terraform-provider-google" -v "ga"`

**Comment by kopachevsky** [comment]
manage to get it working, seems to be initial issue was ruby 5.6.5 version instead 5.6.0, was able to build both providers

**Comment by kopachevsky** [comment]
@rileykarson I think issue could be closed
