### ISSUE TITLE
Make the magician support non-plaintext messages in generated commits

### ISSUE THREAD

**Issue by ndmckinley** [GoogleCloudPlatform/magic-modules#268]
Right now, if you add `any` *interesting* _markdown_, the magician loses its mind and uses "Magic Modules Changes" as the downstream commit message.  This is definitely because I'm naively using an HTML parser to read the markdown's output HTML, and that changes the HTML in a way that I haven't accounted for.

Also worth making the magician pay attention to newlines supposedly separating the title and body of the downstream PR.

**Comment by ndmckinley** [comment]
Also replace the default "Magic Modules Changes" with the title of the upstream PR.

**Comment by SirGitsalot** [comment]
Good enough
