### ISSUE TITLE
update codelab

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#2723]
A few things are out of date right now:
- provider map (https://codelabs.developers.google.com/codelabs/magic-modules/index.html#6)
- id_format (the example one looks to be the current default, so probably good to add something there about what the default is and why one might override it)

That's all I noticed right now, but it's probably worth a quick skim for content to make sure.

**Comment by rileykarson** [comment]
Done. Synced the branches to master + stepped through the codelab and removed irrelevant parts.
