### ISSUE TITLE
Inspec Resource for Kubernetes Service, Deployment and Ingress

### ISSUE THREAD

**Issue by callppatel** [GoogleCloudPlatform/magic-modules#2724]
Looks like we dont have GCP inspec resource available for below three resource. Do we have any backlog item to define it in future.
kubernetes_service
kubernetes_deployment
kubernetes_ingress

**Comment by slevenick** [comment]
I don't believe this is in scope of magic modules or the inspec-gcp generated repo. 

Kubernetes deployments, services and ingresses do not have any specific relation to this project. I would look into other options for writing InSpec controls against kubernetes deployments, potentially:
https://github.com/bgeesaman/inspec-k8s
or
https://blog.chef.io/detect-kubernetes-vulnerabilities-with-inspec/

**Comment by callppatel** [comment]
We have corresponding Terraform resource for Kubernets, currently we do have inspec for container_clusters & container_node_pool

https://www.terraform.io/docs/providers/kubernetes/r/service.html
https://www.terraform.io/docs/providers/kubernetes/r/ingress.html
https://www.terraform.io/docs/providers/kubernetes/r/deployment.html

**Comment by slevenick** [comment]
Yes, there are Terraform resources for Kubernetes, but they are not part of the google provider which Magic Modules generates. They are a separate project: https://github.com/terraform-providers/terraform-provider-kubernetes

Magic Modules only generates the google provider: https://github.com/terraform-providers/terraform-provider-google

**Comment by callppatel** [comment]
Ok.. Got it. Thank you !
