### ISSUE TITLE
gcp_compute_subnetwork_facts -> gcp_compute_subnetwork_info rename missed module_defaults

### ISSUE THREAD

**Issue by zmalone** [GoogleCloudPlatform/magic-modules#2730]
module_defaults allows you to group definitions for all modules in the group/gcp class of Google MagicModules modules, https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html has documentation on this. This feature allows for terse playbooks that don't repeat authorization definitions for every single task.

After the rename of the facts modules to end in the word "info", module_defaults no longer seem to register inside of _info modules, yet they work with the deprecated _facts modules. Could something have been missed in the rename?

**Comment by emilymye** [comment]
@rambleraptor
