### ISSUE TITLE
Instance Group Manager does not support multi-zone

### ISSUE THREAD

**Issue by bryanasdev000** [GoogleCloudPlatform/magic-modules#2742]
Hi!

Update of issue: #561

No support for creating a managed instance group in multiple zones.

Just for the records, what I've doing is create a managed instance group with multiple zone based in southamerica-east1 region with Ansible.

More info: [#42378](https://github.com/ansible/ansible/issues/42378#issuecomment-557604508)

Ref: 
[#561](https://github.com/GoogleCloudPlatform/magic-modules/issues/561)
[#42378 at Ansible repo](https://github.com/ansible/ansible/issues/42378)

**Comment by emilymye** [comment]
@rambleraptor
