### ISSUE TITLE
Add a provider for mgmtconfig

### ISSUE THREAD

**Issue by purpleidea** [GoogleCloudPlatform/magic-modules#28]
It would be nice to have a provider to generate https://github.com/purpleidea/mgmt/ resources.

What's missing is:

1) Documentation or hints on writing such a provider, in particular around listening and handling events, since mgmt supports reactive resources.

2) A developer at Google who'd be willing to help kick off the initial implementation of this.

For more information on (1) please see the introductory article about mgmt: https://purpleidea.com/blog/2016/01/18/next-generation-configuration-mgmt/

Thanks!

**Comment by erjohnso** [comment]
Hiya @purpleidea - mgmt looks like a very great approach!

I'm open to revisiting this down the road, but for now we'll need to put this off in terms of Googlers adding coverage. We're still building out MM core and coverage for many of the more traditional / well-known projects in this space and don't have cycles for something else right now.

However, if you wanted to take a crack at adding mgmt, we could help with reviews.

**Comment by purpleidea** [comment]
@erjohnso I understand. I think the biggest obstacle on my side would be getting up and running. Do you think someone on your team would have cycles for a day or two of in person hacking so that I could get up to speed quickly? That way it wouldn't cost you too much time, and it would save me the overhead of getting familiar with your code base and architecture.

Thanks for the reply!

**Comment by purpleidea** [comment]
(As a technical aside, even though mgmt isn't as well-known yet, it does add the notion of events, so I'm hoping you'd consider it so that events can be handled properly for this and future tools that use it.)

**Comment by purpleidea** [comment]
@erjohnso Much appreciated! Let me know if I can help out with more information in some way. Thanks!

**Comment by purpleidea** [comment]
@rileykarson Why closed? Is this project dead?
