### ISSUE TITLE
Support one-at-a-time updates.

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#281]
Originally, this issue was about adding Cloud Composer support to our downstreams.  That had to be done manually for Terraform (and not at all for Ansible) because Cloud Composer requires a type of update that we don't yet support in Magic Modules.

=================================

https://cloud.google.com/composer/docs/reference/rest/
https://github.com/terraform-providers/terraform-provider-google/issues/1588

- [ ] Ansible
- [x] Terraform

**Comment by ndmckinley** [comment]
This resource, as well as container cluster, need support for an ordered update mechanism, where fields are updated one at a time, in order.  This will probably require an alternate template, at least for update.

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/2475 makes this possible
