### ISSUE TITLE
terraform-google-conversion doesn't add  "enabled: true" to masterAuthorizedNetworkConfig structure for GKE, while terraform-provider-google does

### ISSUE THREAD

**Issue by mmontan** [GoogleCloudPlatform/magic-modules#2933]
I found an inconsistency in the way in which a TF configuration for the container API is converted into a JSON structure by Terraform Conversion project and by the Google Provider project, both created using Magic Modules.

This is creating a false positive in the following rego rule used in Terraform Validator:
https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_gke_master_authorized_networks_enabled_v1.yaml

**Description:** 
1) The rego rule expects to find a "enabled = true" field in the masterAuthorizedNetworkConfig block.The field exists in the JSON representation returned from CAI, and it is part of the official API.
http://google3/cloud/gong/terraform/validator/constraints/templates/gcp_gke_master_authorized_networks_enabled_v1.yaml

2) In the Google Provider, the enabled field is omitted from the configuration:
https://github.com/terraform-providers/terraform-provider-google-beta/blob/812048aa8a13da9f199efc53ca76d7ac39e0f1b7/google-beta/resource_container_cluster.go#L552

The field is added automatically to the call to the API in this function:
https://github.com/terraform-providers/terraform-provider-google-beta/blob/812048aa8a13da9f199efc53ca76d7ac39e0f1b7/google-beta/resource_container_cluster.go#L2344

3) The TF plan --> JSON conversion creates a block without an "enabled" field. Conversion expects to find a "enabled" field in the TF configuration to create it in the JSON representation.
https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/fee03f1c97ac6fc2dfe913441aff854762719c1e/google/container.go#L1094

**Impact**
The rego rule 
https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_gke_master_authorized_networks_enabled_v1.yaml
triggers as a false positive.

**Workaround**
If this cannot be fixed, it's possible to rewrite the rego rule to workaround the problem. I am raising this as an issue as it can create unexpected behaviors.

**Comment by danawillow** [comment]
I'm assuming based on the comment in https://github.com/GoogleCloudPlatform/magic-modules/pull/2939, that this is fixed by that PR. If not, feel free to reopen.
