### ISSUE TITLE
Prevent merge on PRs that would modify Terraform but have no CHANGELOG entry

### ISSUE THREAD

**Issue by paddycarver** [GoogleCloudPlatform/magic-modules#2934]
Ideally we should have an action or bot that would prevent merges of any PR that would impact TPG or TPGB, but would result in an unknown changelog entry.

Unknown changelog entries happen if neither of the following conditions are met:

* at least one \`\`\`release-note:whatever block in the issue body
* the `changelog: no-release-note` label applied to the PR

An unknown changelog can _also_ happen if the entry type (`whatever` in the example above) is not one of our known changelog entry types.

## Open Questions

* Should this be implemented as a check on the downstream repos or on magic-modules? I think the answer impacts / is impacted by the work @ndmckinley is doing with the new magician.
* Should this be implemented as part of hashibot or as a GitHub action? Or, if it's on magic-modules, as part of the magician?

## Chaotic Notes

* Ideally we'd do something that is semi-reusable. Other teams at HashiCorp have expressed interest in generating changelogs, and so there will likely eventually be a "standard solution" for HashiCorp's changelogs. If we build it, people will likely just adopt what we build. If we build something specific to us, we may have to change (eventually, think on the geologic scale) to a standard solution.
  * If there's concern about division of labor because of this,  this can be a me / @megan07 project to solve
* GitHub has a few APIs to prevent merging:
  * We could prevent merge when a rejected review is created and programmatically create a review: https://developer.github.com/v3/pulls/reviews/
  * We can mark commits with statuses: https://developer.github.com/v3/repos/statuses/
  * We can use the new-fangled checks API: https://developer.github.com/v3/checks/
* The problem with marking commits with statuses is that the changelog entry can change without a new commit, meaning a commit's status can change, but there's no way (I can see) with the API to reflect that.
* Checks have a weird quirk:
  > Note: The Checks API only looks for pushes in the repository where the check suite or check run were created. Pushes to a branch in a forked repository are not detected and return an empty pull_requests array.
  * This can be worked around by not subscribing to the pull request edit / label actions, and updating the latest commit's check suite with the results, I believe.
* We can use the same code that generates the CHANGELOG to get a list of the entries that it will generate for a given input: https://godoc.org/github.com/paultyng/changelog-gen/changelog#ReleaseNoteBlocks will use the PR title and PR body to generate the changelog entries, each with a type and text. We should be able to just loop over the results of that and check that if an entry exists, it has an accepted type. If no results are returned, we should look for the `changelog: no-release-note` label.
* We should only run this on PRs that will modify Terraform.
* We can enforce some style guide stuff programmatically, like if there's a service name, making sure the service name doesn't start with a \`, etc.

**Comment by emilymye** [comment]
im going to assign this to us both paddy

**Comment by paddycarver** [comment]
This has been completed.
