### ISSUE TITLE
google_compute_router.bgp.asn should not be required

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/magic-modules#2960]
Through gcloud you are able to create routers without setting an asn while still setting fields in the bgp block:

`$ gcloud compute routers create gcloud-router --network=default --region=us-central1 --set-advertisement-ranges=192.168.10.0 --advertisement-mode=CUSTOM`

We should support the same in Terraform. The easy fix is to change asn to optional and enforce at least one field being set in the bgp block.

Please assign to me, I can implement this.

[Reference](https://github.com/GoogleCloudPlatform/magic-modules/blob/d338896f2c7b1b42057092d271132d550f9114d8/products/compute/api.yaml#L10481)

**Comment by rileykarson** [comment]
Hey @umairidris! Filing an issue against https://github.com/terraform-providers/terraform-provider-google is more useful, this issue tracker isn't used much- it's mostly notes & a lot of it is historical. I'm glad to assign HashiBot to indicate that you've picked up the issue once one is open there.
