### ISSUE TITLE
Terraform nested fields don't get filtered out if unset

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#305]
This means that nested properties can't be Optional+Computed, because we'll always send 0 as the value instead of empty. We have three ways we could fix this:
1. Use `d.GetOkExists` like we do with top-level fields.
2. Use a `ForceSendFields`-style approach where we filter everything out except things we want to be allowed to set to zero.
3. Wait until Terraform 0.12 comes out and see if that gives us an alternative.

**Comment by rileykarson** [comment]
I was looking at the (region| )autoscaler PR (#307) and came across this issue in that code. I'm curious what the caveats to using `d.GetOkExists` are, especially if it's already used on top level fields?

**Comment by danawillow** [comment]
You have to specify the full path, so it's a pain to do for things like sets where you would end up with `d.GetOkExists("foo.32758943.bar")`. I _want_ to say (but need to confirm) that the go client libraries also have this problem, so we'd also have to decide how far we want to stray from them.
