### ISSUE TITLE
Fix sqladmin API change

### ISSUE THREAD

**Issue by megan07** [GoogleCloudPlatform/magic-modules#3109]
We've updated the sqladmin base_url in MM after revendoring to v0.16.0 of the API.  This is a reminder to fix anything that may have been broken.

See context: https://github.com/GoogleCloudPlatform/magic-modules/pull/3099

**Comment by rileykarson** [comment]
Our tests using the generated Database resource failed last night, I think I've got a fix.

**Comment by rambleraptor** [comment]
Part of the reason that this was assigned to me was that Ansible is currently broken, since I said I was fine with breaking the Ansible tests temporarily to let TF merge quicker. 

Please cc me on the TF fix and if it doesn't fix Ansible, I'll make the Ansible fix.

**Comment by rileykarson** [comment]
Yep, I expect it will fix both otherwise I would have left you assigned.

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/3111
