### ISSUE TITLE
URL handling code in core.rb should not be ruby-specific

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#311]
https://github.com/GoogleCloudPlatform/magic-modules/blob/d2a848509ba5880e790ec271639db4fa6c78b911/provider/core.rb#L352-L388

All the URL building code calls build_url, which adds ruby-specific URL logic. Terraform and Ansible override these functions with some of the same logic, but it would be better if they could just call them outright.

**Comment by rambleraptor** [comment]
This has been fixed! URL logic has been moved into api/resource.rb and every provider has a build_url function that uses those api/resource.rb URLs.
