### ISSUE TITLE
Remove abbreviated 'GCS' in compute_resource_policy field

### ISSUE THREAD

**Issue by caieo** [GoogleCloudPlatform/magic-modules#3149]
Cloud Google docs has the description for `snapshotSchedulePolicy.snapshotProperties.storageLocations` as "Cloud Storage bucket storage location of the auto snapshot (regional or multi-regional)." ([linked here](https://cloud.google.com/compute/docs/reference/rest/beta/resourcePolicies)) and no longer allows abbreviated service names. The current `snapshot_properties.storage_locations` field has this description "GCS bucket location in which to store the snapshot (regional or multi-regional)." ([linked here](https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/resource_compute_resource_policy.go#L214)) This is impacting our releases because it's catching this abbreviation and forcing us to manually update. I have a feeling you'll just need to regenerate the resource_compute_resource_policy provider, but haven't been able to act on it.

**Comment by rileykarson** [comment]
Hey! Mind filing against the TPG repo? The fix will get made here, but we use that repo as the canonical issue tracker for Terraform-related stuff.

**Comment by caieo** [comment]
Yeah, filing it now. Sorry for the confusion!
