### ISSUE TITLE
Validate terraform documentation examples

### ISSUE THREAD

**Issue by rosbo** [GoogleCloudPlatform/magic-modules#33]
The goal is to make sure our examples don't have typos or fields that do not exist.

Write a test that do:
- Parse the HCL in the config examples and extract the various fields
- Get the list of fields supported by Terraform
- Make sure all the fields exist, also take care of valid fields not defined in the tf schema such as `depends_on`, `timeout` and so on.

**Comment by rileykarson** [comment]
The followup to #423 will validate these examples, though in a little different of a way than proposed here.

**Comment by rileykarson** [comment]
Closed with #446
