### ISSUE TITLE
Remove 'ForceNew' from ContainerCluster release_channel schema

### ISSUE THREAD

**Issue by caieo** [GoogleCloudPlatform/magic-modules#3423]
TF provider makes this [`release_channel` field](https://github.com/terraform-providers/terraform-provider-google-beta/blob/master/google-beta/resource_container_cluster.go#L830) immutable, but the underlying API seems like this field should actually be mutable (you can [enroll an existing cluster into a release channel](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#enrolling_an_existing_cluster_in_a_release_channel))

**Comment by danawillow** [comment]
Closing in favor of https://github.com/terraform-providers/terraform-provider-google/issues/5846
