### ISSUE TITLE
Google Beta Terraform google_artifact_registry_repository only supports format DOCKER

### ISSUE THREAD

**Issue by trietsch** [GoogleCloudPlatform/magic-modules#3920]
**Note: I'm aware that the preference is to make Terraform specific issues in the Terraform Google repository, however that redirects me to the GA Google provider and the Google Beta provider does not allow issues to be created.**

The current `google-beta` Terraform provider only supports artifact repositories of format `DOCKER`, even though the [API supports other formats](https://cloud.google.com/artifact-registry/docs/reference/rest/v1beta1/projects.locations.repositories#Format).

Could  [magic-modules/products/artifactregistry/api.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/31f5d305e1ade5582f11b46a0ed0704ce67a3c72/products/artifactregistry/api.yaml#L88) be updated with the allowed values `MAVEN` and `NPM`, so that it aligns with the API docs?

This way it would also be made available in the Terraform `google-beta` provider. Thanks!

**Comment by trietsch** [comment]
@rileykarson may I ask what the reason is for closing the issue?

**Comment by rileykarson** [comment]
Sorry! I mass-closed all the issues in this repo, I should have responded directly here since it was recently filed. See https://github.com/GoogleCloudPlatform/magic-modules/issues/3933- we'd prefer if issues go directly to tool repos, Terraform in this case. Mind filing an issue at https://github.com/hashicorp/terraform-provider-google/issues/new/choose?

**Comment by trietsch** [comment]
Ah no worries. Okay, I'll do that. I thought, since my issue concerned the beta provider, that I had to file an issue there. Issues are disabled for that repository however. 
So any issues concerning the beta provider may be filed at the GA provider repo?

**Comment by rileykarson** [comment]
Yep! Sorry for the confusion- we figured closing issues on that repo would make it clear that they should be filed against the GA provider repo but every once and a while that assumption doesn't work out.

Them existing as separate repos is really just an artifact of the fact that each Terraform provider needs to live in a separate repo, the `terraform-provider-repo` is the issue tracker for both.

**Comment by trietsch** [comment]
Great, thanks for clarifying! :)

**Comment by muffl0n** [comment]
@trietsch, did you create an appropriate issue in https://github.com/hashicorp/terraform-provider-google? I cannot find any and I'm not sure if I am just blind. :)

**Comment by trietsch** [comment]
@muffl0n Nope, you're not blind :) I forgot to create it, so it's there now: https://github.com/hashicorp/terraform-provider-google/issues/8486

**Comment by muffl0n** [comment]
Thank you! :)
