### ISSUE TITLE
gauth_credential_serviceaccount_for_function fails

### ISSUE THREAD

**Issue by slevenick** [GoogleCloudPlatform/magic-modules#420]
Calling gauth_credential_serviceaccount_for_function fails due to the self call within that function being undefined.

NoMethodError
-------------
undefined method `gauth_credential_serviceaccount_for_function' for #<Class:0x0000000005a110d0>::Google::GSQL::Instance

Cookbook Trace:
---------------
  /localpath/google-gauth/libraries/google/functions/gauth_credential_serviceaccount_for_function.rb:28:in `gauth_credential_serviceaccount_for_function'

 28>>       self.class.gauth_credential_serviceaccount_for_function(path, scopes)

**Comment by slevenick** [comment]
Seems to be fixed by replacing line 28 with line 24.

 24:        ::Google::Authorization.new.for!(scopes).from_service_account_json!(path)

**Comment by rambleraptor** [comment]
If you look at the `gcompute_image_family` function, it provides another
workaround.

**Comment by slevenick** [comment]
This may have already been fixed, just not updated in supermarket
