### ISSUE TITLE
Go version in Dockerfiles is out of date

### ISSUE THREAD

**Issue by rileykarson** [GoogleCloudPlatform/magic-modules#434]
Since our images are linked to @ndmckinley's Docker Hub account, he'll need to update upstream while making these changes.

https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/containers/go-ruby/Dockerfile pulls in Go 1.9 which has a different `gofmt` output than Go 1.11. Our golang dependency needs an update, along with a new tag of both `go-ruby` and `go-ruby-python` being pushed. Then, all the users of each should use a new tag.

**Comment by ndmckinley** [comment]
Ah, fixed in #438.
