### ISSUE TITLE
Property Overrides should allow you to override Type

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#458]
Some TF resources have not been autogenerated yet. There are certain contexts (ask @craigatgoogle!) where TF wants resources to be Strings, but P/C/A want them to be ResourceRefs.

We need a way to specify a `new_type` on a property_override that will change the type of that property.

**Comment by danawillow** [comment]
This doesn't make much sense to me. The reason why TF would want them to be strings is just because they don't exist in MM yet. If it can be a ResourceRef, that's certainly better.

**Comment by rambleraptor** [comment]
We already have support for this! https://github.com/GoogleCloudPlatform/magic-modules/blob/8697e36dad82b5252086e0095dab6ee2846f77b9/overrides/runner.rb#L159
