### ISSUE TITLE
Proposal: Move the templates/ folder into the provider/ tree

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#487]
Right now, the templates/ folder for Terraform houses both templates and code that gets copied directly, because there isn't a great place for the copied code. provider/terraform/ sort of makes sense for it, but it feels weird right now to have them so far away in the tree.

Proposed structure:
```
magic-modules
|__ provider/
|_____ terraform/
|________ templates/
|________ helpers/
|________ files/
```

This seems to make sense for me for TF, but does it make sense in the other providers?

**Comment by rambleraptor** [comment]
I'm personally not a huge fan of this.

Right now, Puppet + Chef share some template files. InSpec will (probably) be sharing some template files with Chef.

In templates/, we can create shared folders i.e. puppetchef. In provider/, these shared files don't have a great home

**Comment by danawillow** [comment]
Why can't we create shared folders in provider?

**Comment by danawillow** [comment]
Yeah- we already have `templates/puppetchef`, so if we did this it would just reverse to `puppetchef/templates`.

**Comment by rileykarson** [comment]
@rambleraptor What do you think of this now that there's no shared templates?

**Comment by rambleraptor** [comment]
I'm back-and-forth on this personally. I really like the idea of letting all of the provider code sit in one central place. 

But, I feel like the current api-provider-templates structure gives us a clear MVC (model-view-controller) pattern, which is what we've build (model=api/, view=templates/, controller=provider/). In that case, it's nice to have these things split out just to keep that purity.

Reading through that, that sounds like me just being a design pattern purist. I don't have strong opinions for/against.
