### ISSUE TITLE
Use GH title on downstreams instead of "Magic Modules changes"

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#525]
I feel like our GH PR titles are super useful. But, we're bad about copying + pasting that title into the form. All of our downstreams end up being titled "Magic Modules Changes" and that's not super helpful.

It would be nice if the GH title of the MM PR would be used instead of the generic "Magic Modules changes." message.

**Comment by rileykarson** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/946
