### ISSUE TITLE
only run tests on repositories that get changed for a given MM PR

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#536]
If a given PR only affects, say, TF + Ansible, it would be great to be able to skip the puppet/chef tests in the magician run.

**Comment by danawillow** [comment]
@ndmckinley, how much effort do you think this would be? I'm thinking about the near future where all TF PRs are done against MM. This seems like fairly low hanging fruit for speeding up the magician in those cases.

**Comment by ndmckinley** [comment]
A medium amount of effort.  Maybe 2 days, and some added complexity, but not _too_ much added complexity.  How much time would it save?

**Comment by danawillow** [comment]
Ah ok then it's probably not worth it. I think it'd only save a minute or two max per run.

**Comment by rileykarson** [comment]
Since the motivation for this issue was time-saving and we run tests in parallel now, closing this as outdated.
