### ISSUE TITLE
Container Node Pool boot disk type setting is missing (use ssd)

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#560]
Google Kubernetes Engine now has the option to use SSDs as boot disks in node pools. You can set them up on the web UI in the Boot disk type section. I can't find a way to change this setting via the ansible module.

Related: ansible/ansible#47025

**Comment by rileykarson** [comment]
Looks like this is filed against the downstream, so let's track it there.
