### ISSUE TITLE
Compute Instance Group Manager doesn't support multi-zone

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#561]
No support for creating a managed instance group in multiple zones.

related:ansible/ansible#42378

**Comment by rileykarson** [comment]
Unless I'm missing something, I don't think that's an igm feature? Normal igms are zonal. Regional igms have `distributionPolicy.zones[]` but they all need to live in the same region unlike in the original issue where the example has them spread across 2 regions.

**Comment by rileykarson** [comment]
Since this is filed against the downstream, let's track it there.
