### ISSUE TITLE
Some unit tests are hanging (or excruciatingly slow)

### ISSUE THREAD

**Issue by nelsonjr** [GoogleCloudPlatform/magic-modules#73]
Investigate why these puppet/compute tests are running either very slow or hanging:

- spec/gcompute_instance_group_manager_provider_spec.rb
- spec/gcompute_instance_provider_spec.rb
- spec/gcompute_instance_template_provider_spec.rb
- spec/gcompute_target_https_proxy_provider_spec.rb
- spec/gcompute_target_ssl_proxy_provider_spec.rb

**Comment by rambleraptor** [comment]
If I remember correctly, failing tests (that don't fail immediately for Ruby/Rspec related reasons) on Puppet hang.
