### ISSUE TITLE
Add first-class support for new-style (name) self links

### ISSUE THREAD

**Issue by rileykarson** [GoogleCloudPlatform/magic-modules#937]
Newer APIs have a `name` field that has replaced `self_link`; MM was written with older APIs in mind such as Compute, and we need to jump through some hoops to properly support these newer APIs.

AcessContextManager and Stackdriver Monitoring have made that especially clear - they share a few custom flattens/custom code, and could likely share more.

---

One of the biggest differences is how they express CRUD + List verb URLs - `self_link` style APIs explicitly spelled out `projects/{{project}}/location/{{location}}/kind/{{name}}`, but these newer APIs will express RUD as `{{name}}`, while Create and List will be `{{parent}}/kind`. This is (almost?) always a subset of `{{name}}`, but MM doesn't handle this well, expecting them to be styled like a `self_link`.

---

Some APIs generate the `short_name` and we get it from the operation (ACM AccessPolicy), some require it to provided along with the full `name` self link (ACM AccessLevel), and I'm sure there are other variations - is `short_name` common across new-style APIs? (I think I've seen it elsewhere) and can we handle it consistently across resources if so?

---

This issue will break down to something like:
* audit existing MM products to identify all `name` style self links
* Identify patterns across APIs
* Implement shared patterns as part of `api.yaml`

**Comment by rileykarson** [comment]
References are also expected to be fully qualified;

```
organization = "organizations/NNNNNNNNN"
```

instead of also accepting just the id like in old-style APIs:

```
organization = "NNNNNNNNN"
```

We could duplicate this with a method like `addOptionalPrefix` in supported providers that adds the prefix if not present. Is this something we want to do? (It would solve the single-resource case and not the case of the nested parent.)

**Comment by rileykarson** [comment]
Looks like ACM calls it `short_name`, and Stackdriver Monitoring calls it an `id`. Looking the [the docs for UptimeCheckConfigs](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs#resource-uptimecheckconfig), the shape is:

```
projects/[PROJECT_ID]/uptimeCheckConfigs/[UPTIME_CHECK_ID].
```

For comparison, [AccessLevel docs](https://cloud.google.com/access-context-manager/docs/reference/rest/v1beta/accessPolicies.accessLevels) show the format as:

```
accessPolicies/{policy_id}/accessLevels/{short_name}
```

**Comment by chrisst** [comment]
Ah yeah, but from what I can see that's purely in documentation since neither of those apis provide the `id` or `short_name` as separate field.

**Comment by rileykarson** [comment]
Exactly! They expect a full unique reference (`self_link`/`name`) in the API, but that doesn't match what we'd like to do in Terraform, where we likely prefer the short name (ugh this is such an overloaded word here. name as in "my-instance", not as in `name`). There's no consistent naming scheme for the equivalent of what `self_link` resources split out and call the `name`, and part of this issue is deciding on what we will call that.
